matrix:
  include:
  - language: node_js
    node_js:
    - stable
    cache:
      directories:
      - node_modules
    script:
    - yarn install
    - yarn build
    deploy:
      provider: s3
      access_key_id: AKIAXJOW4I5Z2QT4YYEJ
      secret_access_key:
        secure: anUb2/xbO4I6V/HLsj0cdYHFtVUntEL8f3sUgHAt0MrQ8TBRA00zWFR1kH+NOHAwEibUZofPD/tSZeVlgvtCZqFJZVk392VcY13fswxgE3iayg8+wE9PNObeXuKnS/wNECnT6uDXvXaN7DHz/QR08yXKMnYvlEihHZL4iFMy/pUAZalCyAiWeUsLVlwQx+qQbyiDYaHOD9a3G+mUomT9AyrddfWhpPWTHClqBvisKam4eIiQzzgWaI0OZk1AUjwVCR/5JBg8UJBZ1NmWo9DmRx4U1MSuOzgVuZslsbdhUhStvdHK/MPH/QrHH6FKzK1ZkCeQH/B4uDb2kDqXzPoUi0WtOtgQNSB9EMkH6AFx61Z1EIU5+5waVnZg+TSbZ0nD2NMOzMM43eBeis3EiqYt92y6IdM+3tHAb/1UI3NLQPZMwZ4Hzo4tn4ofDpYR1qfJuLkZnIvoDbgMmON7wxE6hJwVR3jD/ny4lEGoi5QTsB4XUOMB4gwM/ue8FDhZwsVO5WdB//f1hW2O6doQT6rE7Oti5Axak7F5m1PjzwBZHRo52MvpWhfaYgJdq6lUCuxI5Ftm75n1gMXQxMhhQ+Vk7EFiCDaZRr4Zhg1pY+0eCxapOpbYWEEJkNZTUXri3ztKb9zegW9J+yxTiVrFngXAfYzWZYSofs8mgEVvPJU8HoM=
      bucket: bms-gen3-dev
      local-dir: build
      upload-dir: datadictionary/$TRAVIS_BRANCH/viz
      skip_cleanup: true
      on:
        repo: bioteam/dictionary-visualizer
        all_branches: true