matrix:
  include:
  - language: node_js
    node_js:
    - stable
    cache:
      directories:
      - node_modules
    script:
    - yarn install
    - yarn build
    deploy:
      provider: s3
      access_key_id: AKIAXJOW4I5Z2QT4YYEJ
      secret_access_key:
        secure: DULjJJgTirMQnr91ZjFBh3OW82DNFHS7iuuvqkn3VY8itNJRwuQA9kGoKpp/OiQ50v3y5Ikyhi0LiRgadjEpj61iqqQZZ4HlnS8W4k+Z4YTgeLjYa6CfOR9ABUPAV2YVEoK0/gogbmNfUiMUlZtksFyC8nKRNpiQ95LlxLf1qC5HZHoAS9nnVI4v+019RJ5OA9zRjpCF68xRnVE5Z7fvbxBv5tuOZyDek9zsDy8Yn818EirX41auu9BsvgQWITeCCkqmBd7ffikGYyaLeKwGBnzhEIdxKyJ2Eio/2VC6kjklr5ngWidsm7wOcWYwnRfEBFmWRNSJ5jARre3BmJQsWx9I0KItaubOr5eIJF5Gy/y7SNsnck2xFqCDGHirgKeqmpSmiGT0VR8lOtH/9/Jvetk6D4obYgsNFzaDXId5OSNkggybYf4ymtcJSnUssNz2xAIcNaTbaGMCfZUBnjHuf+qdXgtEtLecaDRXFm8be3vGkeh1oXwQI4tuSUuPdu0RZZ6lXl+9VO3+OoDVB0tDCgjRQEjD/krS91Loqh0psP1MKCOkvXC4PF7zLEwoA33OyvsmGG/cYAeB9nNDTodPHGzgt4xTg97P+0CFKCa4uFyEqiom7BRR0cf6rekGo7sBHMQJP+mkpZbWk5xHJVDRYNMFiQDPww5zN/MNpopdwWI=
      bucket: bms-gen3-dev
      local-dir: build
      upload-dir: datadictionary/$TRAVIS_BRANCH/viz
      skip_cleanup: true
      on:
        repo: bioteam/dictionary-visualizer
        all_branches: true
