matrix:
  include:
  - language: node_js
    node_js:
    - stable
    cache:
      directories:
      - node_modules
    script:
    - yarn install
    - yarn build
    deploy:
      provider: s3
      access_key_id: AKIAXJOW4I5Z2QT4YYEJ
      secret_access_key:
        secure: HFyVW3949RScVzUxV8wQVN97kWS6+hLhASQzXB66OhxcqBpkGZHvqzh2uN+kOM67TLk5nNXhAin9gO6jOi5I+cwOPk7E8D9sdX9dr1iBZ1CiK3xzm8vZ06IsXNPWVFxaWVFvYVJTMNRIgCz0tLnHk0CsWuT1b3HdHP7hoxAN+s97bvav8ClnB4orNlWSRXhNxDaVStj4tNURCbJxo2Em3uEfrr0TzrpqjHKjCEKK2SbACHgAIx5awb7ftbREU/pveDfW/KIm5WPI4FWct3/3fL7M7Tw/OxCx0UMGm8UzGS2evru1KOYFlwaitwM3V4INXBfn6zk5ZCeU6WNDXka3R+6aSdRZCWZ/E6aklHSXgdtwVu6Dr44yoTHf8heNbiqA63jDnREcVAGedKjci7ag8mSBj1Sm0hV92mU1+HWyDPAXt5E/jYtvspVsa5KWziiWwdMDhUUO8w+Ii1dCikkowmteRob2WASC0tSERdP83T2SCsGYJxse8HfzYp2EtzNHkVu0ghncY4io1dfmHLF8UYWgk3cTRYn92chRyRgWl9H4zBl+yQYDAoFfJSEijVzi0qRrEZEa00e12BBEGNS1bpLM96wx5r/xUoC80OxFdej26EBqEjSbVOOc6a0h/9S3Wc5SDrYQsUSl1bSZtYykIyJSJxLgoSAf2n81HTXk3+k=      
      bucket: bms-gen3-dev
      local-dir: build
      upload-dir: datadictionary/$TRAVIS_BRANCH/viz
      skip_cleanup: true
      on:
        repo: bioteam/dictionary-visualizer
        all_branches: true