matrix:
  include:
  - language: node_js
    node_js:
    - stable
    cache:
      directories:
      - node_modules
    script:
    - yarn install
    - yarn build
    deploy:
      provider: s3
      access_key_id: AKIAXJOW4I5Z2QT4YYEJ
      secret_access_key:
        secure: mhBwfYZPRTr6ozQoaZhcCxtqFn2xKoGlJcoweY6XF91sHUUqryLrQmKW3KHYW030cTorNxvtDbXrT+/EYJ4HtocOCu+ZopmamLzQiutiWWGlSOmlraS1yi2NeQm7uANy4/7O6k3dTOtM959QvBHM46CcSspO6R9RuwCN1Amwh951daMOMR9G+mOuYRKrFEfrRlyXxL1blzv4UXXE+A+gJD/qL/O1c7SJFa3hPyHjrQXyc5s4kVcDUEkCQFsOyi8jYvETRe7g7j+SyZWzS8yNhwkmk+XdOonREntcJQfT+CKQ5NPUA22o9RnOgSaKoMJ0jv2sxB31U3ruRPhkgyZFLXhaCGSl8Ts4XX5PKaUj29NwuHBZIcgKdKOyPVzuomNfeVRpEWVeyQIorg3pXucJxl6gMwlzG0Q5TYLDYCWTGSeXP5hJvFQ5LVXcnOeyrXJGII9uA9iDUsIZrHJTXOtP2np5Y+C1fG6RwvW+BSNQaDnEYoHUe5CQF/i/dZsRkSvfJDHDsNhjZaJULNjrW7KT6OqkBse/a9K7IZlc1qQfDkTqfqIcOE0HsWgAvdJqktAH9juEaVyU2nK1J9uw44BJxsebWoduX7AN6flhiyLZRHD028aqYQha/1WlnsYAysYfAt4JgtxhWGquXkCkX58RArVEqKxwCsXf8H0+DeIgkQA=
      bucket: bms-gen3-dev
      local-dir: build
      upload-dir: datadictionary/$TRAVIS_BRANCH/viz
      skip_cleanup: true
      on:
        repo: bioteam/dictionary-visualizer
        all_branches: true